name: my-first-workflow
run-name: Deployed by @${{ github.actor }}
on: push       
jobs:
  job1: 
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
           pwd
           ls -ltr
           hostname
      - name: Step 2 - Checkout
        uses: actions/checkout@v6.0.2
      - name: Step 3
        run: |
            echo 'pwd' >> myartifact.txt
            mkdir artifacts
            echo 'ls-ltr' >> artifacts/list.txt
            echo 'hostname' >> artifacts/hostname.txt
            hostname
      - name: Step 4 - Upload single file
        uses: actions/upload-artifact@v7.0.0
        with:
          name: single_file
          path: ./myartifact.txt
      - name: Step 5 - Upload from directory
        uses: actions/upload-artifact@v7.0.0
        with:
          name: directory_artifacts
          path: artifacts/
      - name: Step 6 - Upload from multiple paths with exclusions
        uses: actions/upload-artifact@v7.0.0
        with:
          name: multi_paths_with_exclusions
          path: |
            ./myartifact.txt
            artifacts/
            !**/hostname.txt
      - name: Step 7 - Upload from multiple paths without exclusions
        uses: actions/upload-artifact@v7.0.0
        with:
          name: multi_paths_without_exclusions
          path: |
            ./myartifact.txt
            artifacts/
  job2:
    name: Job2
    runs-on: ubuntu-latest
    steps:
      - name: Checking current directory
        run: |
          pwd
          ls -ltr
      - name: Download single file artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: single_file
      - name: Checking current directory post download
        run: |
          pwd
          ls -ltr
